version: "3.8"
services:
  dashboard-api:
    build: ./dashboard-api
    container_name: "dashboard-container"
    ports:
      - 5000:5000
    volumes:
      - ./dashboard-api:/usr/src/app/dashboard-api
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27070:27017
    volumes:
      - ./dashboard-api/init_data/mongodb_data.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  frontend:
    build: ./dashboard
    container_name: "frontend-container"
    ports:
      - 5173:5173
    volumes:
       - ./dashboard:/usr/src/app/dashboard
       - /usr/src/app/my-app/node_modules